### ISSUE TITLE
card due date

### ISSUE THREAD

**Issue by obbardc** [MichaelAquilina/trello-rs#13]
hi, thanks for this crate. It's been really useful!

I am wondering if there is plans to support card due dates in the API, at least getting card due date in the first instance?
I would be interested in adding the support for getting due date, if you are willing to accept PRs? :-)

**Comment by MichaelAquilina** [comment]
Hi @obbardc I did not have any plans to do so yet as it's not a feature I use very often. 

However seeing as you are interested in this feature yourself and are willing to open a PR, go ahead! :)

**Comment by obbardc** [comment]
Would it be possible to bump the version so it can be included on crates.io ? :)

**Comment by MichaelAquilina** [comment]
@obbardc a new version has been released! :)
